version: "3.3"

services:
    
    server:
        build: ./
        command: ./bin/bnetw_server 8888
        ports:
            - 8888:8888

    example_client:
        build: ./
        command: ./example/bin/bnetw_example
        network_mode: host
        depends_on:
            - server